### ISSUE TITLE
위시리스트 관련 API 만들기

### ISSUE THREAD

**Issue by kyupid** [kyu-kim-kr/airbnb#32]
- [x] 추가 API
- [x] 위시리스트 호출 API
- [x] 삭제 API

**Comment by kyupid** [comment]
## 추가 API

User의 속성값으로있는 위시리스트에 새로 들어오는 hotel_id값을 추가하기위해서
1. 원래 가지고 있던 User의 `String wishList`을 `List<String>`으로 먼저 변환해주고,
2. 새로들어오는 hotel_id값을 그 리스트에 `add(hotel_id)`한다.
3. 다시 그 리스트를 String으로 변환해서 User의 wish_list컬럼을 update한다 

3번 과정할땐 WishListDTO 에 `List<String> wishList`에 넣어주고 ~~DTO와 DAO가 통신~~하도록 한다. 
가 아니라 Entity와 DAO가 통신하도록 데이터 처리해줘야할건 DTO까지 전부해주고 Entity로 변환해준다. (Edited)

**Comment by kyupid** [comment]
2번 과정에서 문제 발생

```
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:148) ~[na:1.8.0_275]
	at java.util.AbstractList.add(AbstractList.java:108) ~[na:1.8.0_275]
	at com.team03.airbnb.service.UserService.addNewWishToList(UserService.java:29) ~[main/:na]
```

참고: https://stackoverflow.com/questions/5755477/java-list-add-unsupportedoperationexception

해결: List<String> wishList로 받은 것을 `wishList = new ArrayList<>(wishList);` ArrayList로 다시 만들어줌

**Comment by kyupid** [comment]
3번 과정에서 다시 String으로 변환해주는 로직

```java
    public static String listToString(List<?> list) {
        String result = "";
        for (int i = 0; i < list.size(); i++) {
            if (i == 0) {
                result += list.get(i);
            } else {
                result += ", " + list.get(i);
            }
        }
        return result;
    }
```

괜찮은걸까?

**Comment by kyupid** [comment]
- [x] 추가 API 완료

**Comment by kyupid** [comment]
## 삭제 API (하트해제)

1. 먼저 String으로 되어있는 wish_list를 List<String>으로 변환
2. hotelId와 일치하는 인덱스를 찾아서 `remove(인덱스)`
3. 그 List를 다시 String으로 변환해서 wish_list컬럼을 update

**Comment by kyupid** [comment]
- [x] 삭제 API 완료

**Comment by kyupid** [comment]
## 위시리스트 호출 API

1. DAO에서 `userId`로 User를 먼저 찾는다
2. 그 User에서 `wishList`를 가져온다
3. `wishList`에 있는 번호(`hotelId`)에 따라 `WishListDTO`들을 List에 담아 리턴한다.

**Comment by kyupid** [comment]
3번에서 WishListDTO 들을 List에 담는게 아니라 HotelCardDTO를 리스트에 담아서 리턴

**Comment by kyupid** [comment]
완료
